Features/jenkins script
idealista/jenkins_role pull request #3
Opened 2017-09-29 11:45 UTC by jnogol

Fixes #2 and updates Jenkins version to latest LTS

2017-09-29 11:57 UTC, dortegau approved these changes

2017-09-29 16:33 UTC, dortegau requested changes
Please, add a contributing section/link in the Readme file :)

2017-10-02 07:13 UTC, jnogol commented
Done :v:

2017-10-02 11:41 UTC, jdvr approved these changes

2017-11-02 09:30 UTC, sorobon approved these changes

2017-11-02 10:49 UTC, dortegau approved these changes

2017-11-02 10:50 UTC, merged